# Generated by Django 3.2 on 2022-07-27 15:28

import core.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=12, validators=[core.models.numeric_validator]),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='none', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
